ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DOCTOR_NEW_BOOKING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_VISIT_SUMMARY';
